/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgVistas;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesar
 */
public class frmVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmVentas
     */
    public frmVentas() {
        initComponents();
    }
    
    private String usuario;

    private void Buscar(Object[] datos, int codigoProducto) {
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        Object[] datosR = new Object[6];
        int ttlRows = modelo.getRowCount();
        float Total = Float.parseFloat(txtTotalVenta.getText());
        if (ttlRows == 0) {
            datosR[0] = ttlRows + 1;
            datosR[1] = datos[0];
            datosR[2] = datos[1];
            datosR[3] = datos[2];
            datosR[4] = 1;
            datosR[5] = datos[3];
            modelo.addRow(datosR);
            txtTotalVenta.setText(String.valueOf(Float.parseFloat(String.valueOf(datos[3]))));
        } else {
            for (int i = 0; i < ttlRows; i++) {
                if (codigoProducto == (Integer) tblProductos.getValueAt(i, 1)) {
                    int nuevoCantidad = Integer.parseInt(String.valueOf(modelo.getValueAt(i, 4))) + 1;
                    modelo.setValueAt(nuevoCantidad, i, 4);
                    modelo.setValueAt(datos[3], i, 5);
                    txtTotalVenta.setText(String.valueOf(Total + Float.parseFloat(String.valueOf(datos[3]))));
                }
            }
        }
    }

    public void Limpiar() {
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
        }
        txtTotalVenta.setText("0.0");
    }

    public void Cobrar() {
        try {
            String dinero = txtDinero.getText();
            float Cambio = 0.0f;
            float venta = Float.parseFloat(txtTotalVenta.getText());
            lblCambio3.setText(String.valueOf(Cambio));
            lblCambio3.setForeground(Color.black);
            lblCambio2.setForeground(Color.black);
            if (!"".equals(dinero)) {
                Cambio = Float.parseFloat(dinero) - venta;
                if (Cambio >= 0) {
                    lblCambio3.setForeground(Color.green);
                    lblCambio2.setForeground(Color.green);
                    lblCambio3.setText(String.valueOf(Cambio));
                    btnAceptarCobro.setEnabled(true);
                    
                } else {
                    lblCambio3.setForeground(Color.red);
                    lblCambio2.setForeground(Color.red);
                    lblCambio3.setText(String.valueOf(Cambio));
                    btnAceptarCobro.setEnabled(false);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Introdujo un caracter no numerico");
        }
    }
    
    public void SubirVenta(){
            int totCol = tblProductos.getRowCount();
            Object codigo, cantidad, nombre, marca, precio;
            Date fecha = new Date();
            for (int i = 0; i < totCol; i++) {
                codigo = tblProductos.getValueAt(i, 1);
                nombre = tblProductos.getValueAt(i, 2);
                marca = tblProductos.getValueAt(i, 3);
                cantidad = tblProductos.getValueAt(i, 4);
                precio = tblProductos.getValueAt(i, 5);
                pkgFuncionalidad.ventas.AgregarVenta(codigo, nombre, marca, cantidad, precio, usuario, fecha);
            }
            Limpiar();
            frmCobro.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmCobro = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        lblTotal3 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        lblCambio2 = new javax.swing.JLabel();
        lblCambio3 = new javax.swing.JLabel();
        txtDinero = new java.awt.TextField();
        btnAceptarCobro = new javax.swing.JButton();
        lblTotal1 = new javax.swing.JLabel();
        lblDinero = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        frmLogin = new javax.swing.JFrame();
        lblTituloLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        pfContrasenia = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblCodigoProducto = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        btnCobrar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDuplicar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtTotalVenta = new javax.swing.JTextField();
        lblTotalVenta = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAdminProductos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnLogin = new javax.swing.JMenu();
        miAcceder = new javax.swing.JMenuItem();

        frmCobro.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frmCobro.setTitle("Cobro");
        frmCobro.setBounds(new java.awt.Rectangle(150, 250, 400, 300));
        frmCobro.setMaximumSize(new java.awt.Dimension(450, 300));
        frmCobro.setMinimumSize(new java.awt.Dimension(450, 300));
        frmCobro.setPreferredSize(new java.awt.Dimension(450, 300));
        frmCobro.setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        lblTotal3.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        lblTotal3.setText("0.00");

        lblTotal2.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        lblTotal2.setText("$");

        lblCambio2.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        lblCambio2.setText("$");

        lblCambio3.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        lblCambio3.setText("0.00");

        txtDinero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDinero.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDineroActionPerformed(evt);
            }
        });
        txtDinero.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtDineroTextValueChanged(evt);
            }
        });
        txtDinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDineroKeyPressed(evt);
            }
        });

        btnAceptarCobro.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnAceptarCobro.setText("Cobrar");
        btnAceptarCobro.setEnabled(false);
        btnAceptarCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCobroActionPerformed(evt);
            }
        });

        lblTotal1.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        lblTotal1.setText("Total:");

        lblDinero.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        lblDinero.setText("Dinero:");

        lblCambio.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        lblCambio.setText("Cambio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal1)
                    .addComponent(lblDinero)
                    .addComponent(lblCambio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDinero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotal2)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCambio2)
                        .addGap(18, 18, 18)
                        .addComponent(lblCambio3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAceptarCobro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal3)
                            .addComponent(lblTotal2)
                            .addComponent(lblTotal1))
                        .addGap(16, 16, 16)
                        .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDinero))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCambio3)
                    .addComponent(lblCambio2)
                    .addComponent(lblCambio))
                .addGap(18, 18, 18)
                .addComponent(btnAceptarCobro)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frmCobroLayout = new javax.swing.GroupLayout(frmCobro.getContentPane());
        frmCobro.getContentPane().setLayout(frmCobroLayout);
        frmCobroLayout.setHorizontalGroup(
            frmCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmCobroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frmCobroLayout.setVerticalGroup(
            frmCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        frmLogin.setMaximumSize(new java.awt.Dimension(400, 300));
        frmLogin.setMinimumSize(new java.awt.Dimension(400, 300));
        frmLogin.setResizable(false);

        lblTituloLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloLogin.setText("Acceso de usuarios");
        lblTituloLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTituloLogin.setPreferredSize(new java.awt.Dimension(200, 40));
        lblTituloLogin.setRequestFocusEnabled(false);

        lblUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario :");

        lblContrasenia.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblContrasenia.setText("Contraseña :");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUsuario.setMaximumSize(new java.awt.Dimension(200, 40));
        txtUsuario.setMinimumSize(new java.awt.Dimension(200, 40));
        txtUsuario.setPreferredSize(new java.awt.Dimension(200, 40));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnLogin.setText("Acceder");
        btnLogin.setPreferredSize(new java.awt.Dimension(120, 35));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        pfContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pfContrasenia.setMaximumSize(new java.awt.Dimension(200, 40));
        pfContrasenia.setMinimumSize(new java.awt.Dimension(200, 40));
        pfContrasenia.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout frmLoginLayout = new javax.swing.GroupLayout(frmLogin.getContentPane());
        frmLogin.getContentPane().setLayout(frmLoginLayout);
        frmLoginLayout.setHorizontalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmLoginLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContrasenia)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfContrasenia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmLoginLayout.setVerticalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia))
                .addGap(27, 27, 27)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de ventas");
        setMinimumSize(new java.awt.Dimension(1000, 700));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Codigo del producto", "Nombre ", "Marca", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setMinimumSize(new java.awt.Dimension(700, 500));
        tblProductos.setPreferredSize(new java.awt.Dimension(700, 500));
        tblProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setMinWidth(50);
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblProductos.getColumnModel().getColumn(0).setMaxWidth(50);
            tblProductos.getColumnModel().getColumn(1).setMinWidth(150);
            tblProductos.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(1).setMaxWidth(250);
            tblProductos.getColumnModel().getColumn(3).setMinWidth(200);
            tblProductos.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblProductos.getColumnModel().getColumn(3).setMaxWidth(300);
            tblProductos.getColumnModel().getColumn(4).setMinWidth(100);
            tblProductos.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(4).setMaxWidth(100);
            tblProductos.getColumnModel().getColumn(5).setMinWidth(100);
            tblProductos.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        lblCodigoProducto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblCodigoProducto.setText("Codigo del producto");

        txtCodigoProducto.setEditable(false);
        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoProducto.setMinimumSize(new java.awt.Dimension(200, 30));
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyPressed(evt);
            }
        });

        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnDuplicar.setText("Duplicar");
        btnDuplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplicarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtTotalVenta.setEditable(false);
        txtTotalVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalVenta.setText("0.0");

        lblTotalVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalVenta.setText("Total de la venta:");

        lblVendedor.setText("NO HA ACCEDIDO.");

        lblUser.setText("Usuario: ");

        jMenu1.setText("Administracion");

        mnAdminProductos.setText("Administrar productos");
        jMenu1.add(mnAdminProductos);

        jMenuItem1.setText("Administrar usuarios");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Inventario");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        mnLogin.setText("Usuario");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });

        miAcceder.setText("Cambiar de usuario");
        miAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAccederActionPerformed(evt);
            }
        });
        mnLogin.add(miAcceder);

        jMenuBar1.add(mnLogin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTotalVenta)
                                        .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnDuplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVendedor)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigoProducto)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(363, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoProducto)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDuplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor)
                            .addComponent(lblUser))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txtCodigoProducto.isEditable()) {
            try{
            int codigoProducto = Integer.parseInt(txtCodigoProducto.getText());
            Object[] datos = pkgFuncionalidad.ventas.buscar(codigoProducto);
            if (datos[0] != null) {
                Buscar(datos, codigoProducto);
            }
            txtCodigoProducto.setText(null);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Debe introducir un codigo de producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe iniciar sesion para poder realizar operaciones");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        int[] NumRows = tblProductos.getSelectedRows();
        float totalVenta = Float.parseFloat(txtTotalVenta.getText());
        for (int i = NumRows.length - 1; i >= 0; i--) {
            totalVenta -= Float.parseFloat(modelo.getValueAt(NumRows[i], 5).toString());
            modelo.removeRow(NumRows[i]);
            txtTotalVenta.setText(String.valueOf(totalVenta));
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDuplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicarActionPerformed
        try {
            int[] numrow = tblProductos.getSelectedRows();
            float totalNuevo = Float.parseFloat(txtTotalVenta.getText());
            int cantidadNuevo;
            for (int i = 0; i < numrow.length; i++) {
                cantidadNuevo = (Integer) tblProductos.getValueAt(i, 4);
                totalNuevo += (Float.parseFloat(tblProductos.getValueAt(numrow[i], 5).toString()) * cantidadNuevo);
                tblProductos.setValueAt(cantidadNuevo*2, numrow[i], 4);
                txtTotalVenta.setText(String.valueOf(totalNuevo));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDuplicarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDineroActionPerformed

    private void txtDineroTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtDineroTextValueChanged
        Cobrar();
    }//GEN-LAST:event_txtDineroTextValueChanged

    private void txtDineroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDineroKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            SubirVenta();
        }
    }//GEN-LAST:event_txtDineroKeyPressed

    private void btnAceptarCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCobroActionPerformed
        SubirVenta();
    }//GEN-LAST:event_btnAceptarCobroActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        if (txtCodigoProducto.isEditable()) {
           
        frmCobro.setVisible(true);
        lblTotal3.setText(txtTotalVenta.getText()); 
        }else JOptionPane.showMessageDialog(null, "Debe iniciar sesion para poder realizar operaciones");
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void txtCodigoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            int codigoProducto = Integer.parseInt(txtCodigoProducto.getText());
            Object[] datos = pkgFuncionalidad.ventas.buscar(codigoProducto);
            if (datos[0] != null) {
                Buscar(datos, codigoProducto);
            }
            txtCodigoProducto.setText(null);
        }
    }//GEN-LAST:event_txtCodigoProductoKeyPressed

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        frmLogin.setVisible(true);
    }//GEN-LAST:event_mnLoginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String user = txtUsuario.getText();
        String pss = String.valueOf(pfContrasenia.getPassword());
        usuario = pkgFuncionalidad.accesoUsuarios.Acceso(user, pss);
        if (!usuario.equals("")) {
            txtCodigoProducto.setEditable(true);
            lblVendedor.setText(usuario);
            frmLogin.dispose();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void miAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAccederActionPerformed
        frmLogin.setVisible(true);
    }//GEN-LAST:event_miAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmVentas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarCobro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnDuplicar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JFrame frmCobro;
    private javax.swing.JFrame frmLogin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCambio2;
    private javax.swing.JLabel lblCambio3;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblTotal3;
    private javax.swing.JLabel lblTotalVenta;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JMenuItem miAcceder;
    private javax.swing.JMenuItem mnAdminProductos;
    private javax.swing.JMenu mnLogin;
    private javax.swing.JPasswordField pfContrasenia;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCodigoProducto;
    private java.awt.TextField txtDinero;
    private javax.swing.JTextField txtTotalVenta;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
